spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tast1?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 7777